spring:
  profiles:
    include:
        - aws
        - credentials
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 100MB
file:
  upload:
    location: /Users/user/Desktop

cloud:
  aws:
    credentials:
      accessKey: AKIA4WDD7VUU7N2YH5NZ
      secretKey: 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
    s3:
      bucket: jaeminstorage
    region:
      static: ap-northeast-2
    stack:
      auto: false
