spring:
  profiles.active: local
  # 데이터 소스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth_login?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PWD}

  # JPA 설정
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

  # Security OAuth
  security:
    oauth2.client:
      registration:
        google:
          clientId: ${Google_Client_Id}
          clientSecret: ${Google_Client_Secret}
          scope:
            - email
            - profile
        facebook:
          clientId: ${FaceBook_Client_Id}
          clientSecret: ${FaceBook_Client_Secret}
          scope:
            - email
            - public_profile
        naver:
          clientId: ${Naver_Client_Id}
          clientSecret: ${Naver_Client_Secret}
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          scope:
            - nickname
            - email
            - profile_image
          clientName: Naver
        kakao:
          clientId: ${Kakao_Client_Id}
          clientSecret: ${Kakao_Client_Secret}'
          clientAuthenticationMethod: post
          authorizationGrantType: authorization_code
          redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
          scope:
            - profile_nickname
            - profile_image
            - account_email
          clientName: Kakao
      # Provider 설정
      provider:
        naver:
          authorizationUri: https://nid.naver.com/oauth2.0/authorize
          tokenUri: https://nid.naver.com/oauth2.0/token
          userInfoUri: https://openapi.naver.com/v1/nid/me
          userNameAttribute: response
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me
          userNameAttribute: id

# 토큰 관련 secret Key 및 RedirectUri 설정
jwt:
  secretToken: ${Secret_Token}
  accessTokenExp: ${ACCESS_EXP}
  refreshTokenExp: ${REFRESH_EXP}
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}

